language: python

python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "pypy3"

matrix:
  allow_failures:
    # PyTest breakage
    - python: "3.5"
    # Vido doesn't run on 3.2
    - python: "3.2"
    # PyPy stdlib is still 3.2
    - python: pypy3

install:
- uname -a
- lsb_release -a
- python3 --version
- pypy3 --version
- sudo touch /etc/suid-debug
# Travis has a python3, but the /usr/bin/python3 command is Python 3.2, because it's an ancient LTS
- sudo ln -Tsf ~/virtualenv/python3.3.*/bin/python3 /usr/bin/python3
- sudo apt-get -y install libffi-dev btrfs-tools
- which python3
- which pypy3
- pip install cffi pytest
- git clone https://github.com/g2p/vido.git -b for-travis
- curl --compressed -LO https://github.com/g2p/kernels/raw/master/linux.uml
- chmod +x linux.uml
- pip install .

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

script:
- time vido/vido --kernel=./linux.uml -- python3 -Wd -bb -Wignore:::site -Wignore:::cffi.verifier -Wignore:::_pytest.main -Wignore:::_pytest.assertion.oldinterpret -m pytest --capture=no bedup/

