language: python

python:
- "3.3"
- "3.4"
- "3.5"
- "pypy3"

matrix:
  allow_failures:
    # Neither vido nor bedup run on 3.2, PyPy stdlib is still 3.2
    - python: pypy3

install:
- uname -a
- lsb_release -a
- python3 --version
- pypy3 --version
- sudo touch /etc/suid-debug
# Travis has a python3, but the /usr/bin/python3 command is Python 3.2, beurk
- sudo apt-get -y install libffi-dev btrfs-tools
- which python3
- which pypy3
- pip install cffi pytest pytest-cov coveralls git+https://github.com/g2p/vido.git@for-travis
- curl --compressed -LO https://github.com/g2p/kernels/raw/master/linux.uml
- chmod +x linux.uml
- pip install .
- sudo locale-gen en_US.UTF-8

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

script:
- time LC_ALL=en_US.UTF-8 vido --pass-env LC_ALL --kernel=./linux.uml -- python3 -Wd -bb -Wignore:::site -Wignore:::cffi.verifier -Wignore:::_pytest.main -Wignore:::_pytest.assertion.oldinterpret -m pytest --cov=bedup --capture=no bedup/

after_success:
- coveralls

