language: python

install:
- uname -a
- lsb_release -a
- pypy --version
- sudo touch /etc/suid-debug
- sudo aptitude -y install libffi-dev btrfs-tools
- pip install --use-mirrors tox cffi

# PyPy compat: whenever https://launchpad.net/~pypy/+archive/ppa
# gets a CFFI-compatible build (not in a release as of yet).
# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.
script: PIP_USE_MIRRORS=true tox -e py33,py32,py27

