language: python

install:
- uname -a
- lsb_release -a
- pypy --version
- sudo touch /etc/suid-debug
- sudo apt-get -y install libffi-dev btrfs-tools
- pip install --use-mirrors tox cffi

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

script:
- wget -c http://uml.devloop.org.uk.nyud.net/kernels/kernel64-3.7.10.bz2 # 37M
- bunzip2 -k kernel64-3.7.10.bz2
- chmod +x kernel64-3.7.10
# Travis has PyPy 1.9 which is too old (want a PPA to upgrade).
- ./kernel64-3.7.10 rootfstype=hostfs rw init=~+/uml-runner "HOME=$HOME" "PATH=$PATH" PIP_USE_MIRRORS=true mem=128M quiet BEDUP_CMD="tox%20-e%20pypy" \
    || echo "Ignoring PyPy failures on Travis"
- ./kernel64-3.7.10 rootfstype=hostfs rw init=~+/uml-runner "HOME=$HOME" "PATH=$PATH" PIP_USE_MIRRORS=true mem=128M quiet BEDUP_CMD="tox%20-e%20py33,py32,py27"

