language: python

install:
- uname -a
- lsb_release -a
- pypy --version
- sudo touch /etc/suid-debug
- ls -Al /dev/loop* ||true
# https://www.kernel.org/pub/linux/utils/util-linux/v2.21/v2.21-ReleaseNotes
# Ubuntu doesn't ship util-linux 2.21 as of 2013-02 (nor does Debian)
- bash -c 'cd /dev; sudo MAKEDEV loop'
- ls -Al /dev/loop* ||true
- sudo apt-get -y install libffi-dev btrfs-tools
- pip install --use-mirrors tox cffi

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

# Ignore PyPy failures on Travis.
# Travis has PyPy 1.9 which is too old (want a PPA to upgrade).
script:
- export PIP_USE_MIRRORS=true
- tox -e pypy || true
- tox -e py33,py32,py27

