language: python

install:
- sudo aptitude update
- sudo aptitude -y install libffi-dev btrfs-tools
- pip install --use-mirrors https://bitbucket.org/cffi/cffi/get/default.tar.gz
- pip install --use-mirrors tox
- git submodule update --init

# PyPy compat: whenever https://launchpad.net/~pypy/+archive/ppa
# gets a CFFI-compatible build (not in a release as of yet).
script: tox -e py32,py27,py26

