language: python

install:
- uname -a
- lsb_release -a
- pypy --version
- env
- export PIP_USE_MIRRORS=true
- export PIP_DOWNLOAD_CACHE=~/.cache
- env |grep -i pip || echo "no env vars"
- cat ~/.pip/pip.ini || echo "no pip.ini"
- pip install cffi
- ls -R $PIP_DOWNLOAD_CACHE

script:
- true

