language: python

install:
- uname -a
- lsb_release -a
- sudo touch /etc/suid-debug
- sudo aptitude -y install libffi-dev btrfs-tools
- pip install --use-mirrors tox cffi

# PyPy compat: whenever https://launchpad.net/~pypy/+archive/ppa
# gets a CFFI-compatible build (not in a release as of yet).
script: tox -e py33,py32,py27

