language: python

install:
- uname -a
- lsb_release -a
- pypy --version
- sudo touch /etc/suid-debug
- sudo apt-get -y install libffi-dev btrfs-tools
- pip install --use-mirrors tox cffi

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

# Ignore PyPy failures on Travis.
# Travis has PyPy 1.9 which is too old (want a PPA to upgrade).
script:
- export PIP_USE_MIRRORS=true
- tox -e pypy || true
- tox -e py33,py32,py27

