language: python

python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "pypy3"

install:
- uname -a
- lsb_release -a
- python3 --version
- pypy3 --version
- sudo touch /etc/suid-debug
# Travis has a python3, but the /usr/bin/python3 command is Python 3.2, beurk
- sudo apt-get -y install libffi-dev btrfs-tools
- which python3
- which pypy3
- pip install cffi pytest git+https://github.com/g2p/vido.git@for-travis
- curl --compressed -LO https://github.com/g2p/kernels/raw/master/linux.uml
- chmod +x linux.uml
- pip install .

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

script:
- time vido --kernel=./linux.uml -- python3 -Wd -bb -Wignore:::site -Wignore:::cffi.verifier -Wignore:::_pytest.main -Wignore:::_pytest.assertion.oldinterpret -m pytest --capture=no bedup/

