language: python

install:
- uname -a
- lsb_release -a
- sudo aptitude -y install libffi-dev btrfs-tools
- pip install --use-mirrors tox https://bitbucket.org/cffi/cffi/get/default.tar.gz

# PyPy compat: whenever https://launchpad.net/~pypy/+archive/ppa
# gets a CFFI-compatible build (not in a release as of yet).
script: tox -e py32,py27,py26

