language: python

install:
- uname -a
- lsb_release -a
- pypy --version
- sudo touch /etc/suid-debug
- sudo aptitude -y install libffi-dev btrfs-tools
- pip install --use-mirrors tox cffi

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

# Run the tests a second time without pypy and without py33.
# Travis doesn't install py33 (promised Real Soon Now™, see
# travis-ci/travis-cookbooks#89), and has PyPy 1.9 which is
# too old (want a PPA to upgrade).
script: PIP_USE_MIRRORS=true tox || tox -e py32,py27

